### ISSUE TITLE
Clear pending duels on duel accept

### ISSUE THREAD

**Issue by xDestx** [MemeDistributionCo/MDCBot#22]
**User A, User B, and User C**

If **User B** and **User C** do
`--duel @UserA`

that means **UserA** is in _two_ different pending duels. When **UserA** accepts one, they will still be able to accept the other duel as well, and this is a potential issue.

Proposed fix: Find all duels that the user is pending in on duel accept, and disband all of them (try making Disband no event invoke to stop the bot from sayin GG for every one)

**Comment by Brunswick-Khorasan** [comment]
Is currently in the `feature22_branch` branch

**Comment by xDestx** [comment]
Reviewed and it looks like it works so 👍
