### ISSUE TITLE
Player can force duel with other player

### ISSUE THREAD

**Issue by Brunswick-Khorasan** [MemeDistributionCo/MDCBot#23]
For example, consider the following log:
```
Alice: --duel @Eve
Alice: --duel accept @Eve
Bot: @Eve, it is your turn to attack
```
Note that Eve was taken into the duel, even without saying anything

**Comment by xDestx** [comment]
Will do

**Comment by Brunswick-Khorasan** [comment]
Closing because Pull Request #31 is now in v2.2.0 branch
