### ISSUE TITLE
Duel stats

### ISSUE THREAD

**Issue by xDestx** [MemeDistributionCo/MDCBot#25]
Keep win / loss stats (more to come?) (streak?) for players

**Comment by Brunswick-Khorasan** [comment]
Do you think it should be just for the bot's runtime, or should it be in a file? I'm thinking that it should be just a variable, but what do you think?

**Comment by xDestx** [comment]
File imo. It would be cooler to see your stats over time. People don't duel every day, and my computer falls asleep typically once a day. This means stats would be reset every day which wouldn't be very effective.
