### ISSUE TITLE
Role requests

### ISSUE THREAD

**Issue by Brunswick-Khorasan** [MemeDistributionCo/MDCBot#27]
Allow people to request roles for games they play, like g_overwatch, g_civ, etc.

**Comment by xDestx** [comment]
Proposed commands
--game join <game>
--game leave <game>

No role needed

**Comment by xDestx** [comment]
Also, have it delete the `--game` command and the confirmation message after like 10 seconds or so

**Comment by xDestx** [comment]
Solved in #33
